src/cli.js, src/commands/build/sitesgenerator.js, src/commands/init/repositoryscaffolder.js, src/i18n/translationfetchers/localfileparser.js, tests/i18n/translationfetchers/localfileparser.js
This PR has SitesGenerator creating a Translator instance per locale. This
instance is used to create the localized HBS helpers needed to build the locale's
pages.
A couple other small changes were included in this PR. The RepositoryScaffolder
had a bug where it generated a Jambo config with a dirs.translsations attribute.
This should be dirs.translations. The LocalFileParser was changed to gracefully
handle the case when translation files don't exist for a locale.
Added unit tests for the new LocalFileParser behavior. Locally, I created a Jambo
site with a French locale. I provided some French translations. One of my custom
partials used the new translate helper with interpolation. Confirmed that the
text was translated correctly. I also verified that if I tried …
=> Create localized instance of Translator in SitesGenerator.

tests/fixtures/extract/expectedjson.js, tests/fixtures/extract/translations.hbs, tests/fixtures/extract/translations.js
I thought this wouldn't work with handlebars because it changed the syntax coloring in my editor.
But it does!
TEST=auto
=> Change extractor unit tests to use double braces

src/commands/build/sitesgenerator.js
This commit changes envvarparser to only parser out an env object
with the env keys that are asked for, instead of the entire environment.
TEST=manual
run jambo build before changes, see entire process.env printed
run jambo build after changes, see only JAMBO_INJECTED_DATA printed
=> sitesgenerator: only print jambo injected data not entire process.env

src/commands/build/sitesgenerator.js, src/i18n/translator/translator.js, tests/fixtures/translations/fr-FR.po, tests/i18n/translationfetchers/localfileparser.js, tests/i18n/translator/translator.js
Adds a translateWithContext HBS helper to Jambo. Interpolation is also supported.
The Translator class now has a translateWithContext method.
J=SLAP-464
Added new unit tests for Translator.translateWithContext that include simple translations with context and interpolated translations with context.
I also tested a local french jambo site with a partial that invokes the helper
=> Add translateWithContext helper

src/commands/import/themeimporter.js
TEST=manual
J=SLAP-560
Test that there is no change if the locale_config.json file is not present, using the current theme version and the following commands:
```
command jambo init
command jambo import --theme answers-hitchhiker-theme
```
Then test using the same commands but adding a line to check out the "locale-config" branch of the answers-hitchhiker-theme, which has the locale_config.json file, see it copied.
=> Import Theme: copy localization config file if exists

src/commands/build/sitesgenerator.js, src/partials/models/translateinvocation.js, src/partials/partialpreprocessor.js, tests/fixtures/partials/processedcomponent.js, tests/fixtures/partials/processedtemplate.hbs, tests/fixtures/partials/rawcomponent.js, tests/fixtures/partials/rawtemplate.hbs, tests/partials/partialpreprocessor.js
This PR adds the PartialPreprocessor class. This class performs some processing
on partials before Jambo registers them with Handlebars. Specifically, it looks
to transpile all usages of the 'translate' helper from a partial. If the
translation can be resolved at compile-time, the 'translate' call is replaced
with the translated string. If the translation must be done at run-time, the
call is replaced with a call to the SDK's new run-time translation methods.
Translations must be done at run-time if they require pluralization or
interpolation.
Currently, the transpilation only works for JS partials. A subsequent PR will
add support for normal .hbs partials as well.
The Translator class will need to be updated to support run-time translations.
Specifically, the translatePlural method will …
=> Add a preprocessor for all partials registered with Handlebars.

src/commands/build/sitesgenerator.js
The new PartialPreprocessor class makes it such that all translation happens either before HBS compilation or after, during run-time. The 'translate', 'translatePlural', and 'translateWithContext' helpers provided by Jambo have been made redundant with this addition and should no longer be used.
TEST=none
=> Remove unused translation Handlebars helpers

src/i18n/translator/translator.js, tests/fixtures/partials/processedcomponent.js, tests/fixtures/partials/processedtemplate.hbs, tests/i18n/translator/translator.js, tests/partials/partialpreprocessor.js
This PR updates the Translator's main methods to support run-time translation.
Specifically, 'translate' and 'translateWithContext' were changed so that if
the translation requires interpolation, a translated format string is
returned. This way, the correct interpolation values can be computed at
run-time and passed in. The 'translatePlural' method returns a map containing
all translated singular and plural forms of the phrase. At run-time, the count
can be computed and used to choose the right translated form. These forms also
support run-time translation.
J=SLAP-557
TEST=auto
Updated existing unit tests for the Translator.
=> Update the Translator to support run-time translations.

src/commands/build/globalconfiglocalizer.js, src/models/configurationregistry.js
Previously in cases where there was no "locale" specified in the global config, we would create a localized global config with locale set to the empty string. Since missing locale isn't the same thing as empty string locale, only add "locale" to the global config if it's present. Also updated a console log to be clearer.
TEST=manual,unit
J=SLAP-561
Test locally with a site with no locale_config and a global_config without a "locale". Run `jambo build`, print global config from template and see locale is absent. Test setting locale to "en", jambo building, then see locale: "en" printed in template. Test setting locale to empty string and see locale: "" printed in template.
=> Add support for global_configs that do not have any locale information

src/commands/build/pagewriter.js, src/commands/build/sitesgenerator.js, src/commands/build/templatedirector.js, src/models/page.js, src/models/pagetemplate.js, src/models/partial.js, tests/commands/build/templatedirector.js, tests/models/generateddata.js, tests/models/page.js
We need to preprocess all the partials for internationalization work. This means we can't read in the file right before we write it, so instead of storing the templatePath on the page it makes more sense to store the contents of that file. This makes it simpler to preprocess or transpile the contents of the template file. 
TEST=unit,manual
Run `jambo build && grunt webpack` on local internationalized test site. View pages in browser and confirm they look as expected.
=> Update PageTemplates to use a Partials domain model

src/cli.js, src/commands/build/sitesgenerator.js, src/commands/card/cardcreator.js, src/commands/directanswercard/directanswercardcreator.js, src/commands/import/themeimporter.js, src/commands/init/repositoryscaffolder.js, src/commands/override/themeshadower.js, src/commands/upgrade/themeupgrader.js, src/errors/systemerror.js, src/errors/usererror.js, src/utils/errorutils.js, src/utils/gitutils.js, src/utils/jamboconfigutils.js
Jambo now returns the following codes:
| Exit code | Reason              |
|-----------|---------------------|
| 0         | Success             |
| 1         | Unhandled Exception |
| 13        | UserError           |
| 14        | SystemError         |
This commit adds an exitWithError() function to errorutils which will print the error and then terminate jambo. If a UserError or SystemError is passed to exitWithError, then jambo will exit with codes 13 or 14 respectively. Any other Errors passed will terminate jambo with exit code 1. I chose codes 13 and 14 since node process has definitions for most codes between 2 and 12.
In general, a UserError or a SystemError should be thrown so that they can be caught inside src/cli.js and passed to exitWithError().
J=SLAP-538
TEST=manual
I …
=> Return proper error codes

src/commands/build/pagepartialdirector.js
TEST=manual
Test locally with a a config/locations.es.json and a pages/locations.html.hbs, see Spanish locations page is built.
=> Use page template from the default locale if no other page template exists

src/commands/build/pagesetsbuilder.js
Previously this was throwing a "Cannot read property 'find' of undefined" error. Updating to print a helpful message and continue without generating a page set when missing page templates.
TEST=manual
Run `jambo build` locally for a site without page templates for a given locale.
=> Add error message if missing all page templates for a locale

src/models/localizationconfig.js, tests/models/localizationconfig.js
Previously the default url format was using the baseLocalePattern, and all others were using the defaultLocalePattern. It should be the opposite.
TEST=manual,unit
On local test site, generate pages with the default locale and an additional locale, see output paths use expected url formatting pattern.
=> Reverse conditional to use the correct url formatting pattern for a locale

src/commands/build/pageconfigdecorator.js, src/commands/build/pagesetsbuilder.js, src/commands/build/pagetemplatedirector.js, src/commands/build/pagewriter.js, src/commands/build/sitesgenerator.js, src/constants.js, src/models/configurationregistry.js, src/models/generateddata.js, src/models/localizationconfig.js, src/models/pageconfig.js, src/models/pagetemplate.js, tests/commands/build/pageconfigdecorator.js, tests/commands/build/pagetemplatedirector.js, tests/models/configurationregistry.js, tests/models/generateddata.js, tests/models/pageconfig.js, tests/models/pagetemplate.js
There was an issue where the localized-pages branch was not backwards compatible if the locale-specific naming scheme was used in page files for locales that *didn't* match the locale in the global_config. For example, if the locale in my global_config was "en", but I had a page files: `config/name.es.json` and `page/page.es.html.hbs`, they would be considered files for the "es" locale, and would not be generated, even though we didn't have a locale_config. Eliminated defaulting to the global_config's locale since we were only using it for a key in an Object and it was complicating the fallback logic.
TEST=manual,unit
Tested on a repo with files using the locale-specific naming scheme without a locale_config.json file; verified that the following pages were generated: locations.es.html, …
=> Update generation to support backwards compatiblity with locale naming

src/commands/build/sitesgenerator.js
Fixed a small bug where an Error is caught with the name "e" but is referred to as "err"
J=none
TEST=manual
I reproduced the error manually and confirmed the proper Error is now thrown
=> Fix parsing config error

src/handlebars/handlebarspreprocessor.js, tests/fixtures/handlebars/processedtemplate.hbs, tests/fixtures/handlebars/rawcomponent.js
When there is a static translation in hbs, we dont want to wrap it in quotes.
Originally, this item was going to also not wrap static translateJS results
in quotes as well, but after taking another look that seemed confusing, since
translateJS would return a javascript string if it was a runtime translation,
but the raw(?) text if it was a static translation. In order to know whether
to wrap a translate helper in quotes you would have to think about whether
this was something that would be statically translated i.e. (no interpolation or
plurals). This seemed like something that could end up very frustrating.
Instead, with this pr {{translateJS}} will always compile to a js string, and
{{translate}} will always compile down to raw text without quotes,
whether runtime or not.
J=SLAP-592 …
=> dont wrap static {{translate}} results with quotes

src/handlebars/models/translateinvocation.js, tests/handlebars/models/translateinvocation.js
This commit updates the TranslateInvocation model to use the
Handlebars parser for parsing out properties of the invocation.
J=SLAP-599
wrote unit tests for TranslateInvocation
added a page with contents `{{{read 'partials/temp'}}}`
and partials/temp.hbs with contents 
```hbs
{{translate phrase='Hello my name is [[name]]' name=card.name}}
blahasdf
```
on running jambo build got result 
```hbs
{{ runtimeTranslation phrase='Bonjour, mon nom est [[name]]' name=card.name }}
blahasdf
```
=> TranslateInvocation: update to use the Handlebars parser

src/i18n/translator/translator.js, tests/fixtures/translations/fr.po, tests/i18n/translator/translator.js
Add tests that confirm that the translator handles intermixed markdown as expected
J=SLAP-581
In addition to automatic tests, I also tested the handlebars translate helper in an internationalized jambo site. The mixed markdown fails due to the regex not picking characters including "<" and ">". Oliver's switch to the handlebars parser fixes this issue: https://github.com/yext/jambo/pull/98
=> Intermixed markdown

src/handlebars/handlebarspreprocessor.js, tests/handlebars/handlebarspreprocessor.js
This commit passes the plural form to translatePlural, so that
in cases when there is no plural form found in the translation data,
it will default to whatever this passed in value is.
J=SLAP-593
TEST=auto
Add unit test for this case. See that if I use the old code, it breaks,
but new code passes this test.
=> handlebarspreprocessor: pass plural form to translatePlural

tests/fixtures/handlebars/processedcomponent.js, tests/fixtures/handlebars/processedtemplate.hbs, tests/fixtures/handlebars/rawcomponent.js, tests/fixtures/handlebars/rawtemplate.hbs
The previous change of making the regex non greedy fixed the issue of
having multiple translate invocations on a single line bugging out,
so this pr just adds some coverage for that behavior
J=SLAP-591
TEST=auto
updated unit test fixtures
=> handlebarspreprocessor: update tests to cover 2 translates per line

tests/fixtures/extractions/combined.pot, tests/fixtures/extractions/rawtemplate.hbs, tests/fixtures/extractions/rawtemplate.pot
Add a test that confirms the extractor escapes double quotes when generating .POT files. The test also confirms that escaping single quotes is handled properly.
J=SLAP-581
TEST=auto
Ran the unit tests
=> Test intermixed markdown extraction

src/handlebars/handlebarspreprocessor.js, tests/fixtures/handlebars/processedcomponent.js, tests/fixtures/handlebars/processedtemplate.hbs, tests/fixtures/handlebars/rawcomponent.js, tests/fixtures/handlebars/rawtemplate.hbs, tests/handlebars/handlebarspreprocessor.js
This commit makes the regex non-greedy so that it ends its match on the
first closing mustache found, instead of the last. This fixes both commented out
translation helpers and multiple translation helpers on a single line.
J=SLAP-591, SLAP-595
added unit tests
test jambo build locally with a commented out helper, and also two helpers on the same line
=> handlebarspreprocessor: make translate helper regex non-greedy

src/i18n/extractor/translationextractor.js, tests/fixtures/extractions/combined.pot, tests/fixtures/extractions/rawtemplate.hbs, tests/fixtures/extractions/rawtemplate.pot
Noticed a bug while working on the sdk extractor, the extractor
would only detect {{translate calls on the first level of a
handlebars AST, and any {{translate calls nested within any
handlebars logic would not be detected. This is fixed by
updating the extractor to use Handlebars.Visitor, which
automatically visits all nodes no matter the depth.
TEST=auto
updated unit tests, see that old code would fail but new code passes
=> TranslationExtractor: use visitor instead of looping over first layer of statements

src/i18n/translator/translator.js, tests/fixtures/handlebars/processedtemplate.hbs, tests/fixtures/handlebars/rawtemplate.hbs, tests/fixtures/translations/fr-FR.po, tests/handlebars/handlebarspreprocessor.js, tests/i18n/translationfetchers/localfileparser.js, tests/i18n/translator/translator.js
Fixes the translator when translating phrases with periods or colons
By default, i18next uses periods to separate keys and colons to separate namespaces. This PR disables that functionality and allows us to use translations with a colon or period in the key.
J=none
Added tests that confirm the preprocessor and the translator can handle phrases with periods and colons. Manually tested the translator on an internationalized answers site.
=> Fix translation of phrases with colons and periods

src/commands/build/sitesgenerator.js, src/handlebars/handlebarspreprocessor.js
Since single-locale sites don't have a translator they could return an error much later in the HandlebarsProcessor `Cannot read property 'translate' of undefined`. Even same-language content could be used with the translate helpers for interpolation or pluralization, so we can't simply skip the pre-processing. Instead, we will always require a translator for pre-processing, even if the translator has no translations.
TEST=manual
=> Create translator for each PageSet even if no locale config if provided

src/commands/build/sitesgenerator.js, src/i18n/translationfetchers/localfileparser.js
J=SLAP-615
TEST=manual
1 - Test with a single-locale site (a site without a locale_config.json). Confirm that `jambo build` succeeds and output files look normal. 
2 - Test with a multi-locale site with out any translation files. 
For the locales in the locale_config without a "translationFile" entry, the default [locale].po fileName is used. If that file is not present, a UserError thrown, e.g.:
```
Cannot find translation file for 'es' at 'translations/es.po'
UserError: Cannot find translation file for 'es' at 'translations/es.po'
at LocalFileParser.fetch (/Users/agrow/repo/jamboree/src/i18n/translationfetchers/localfileparser.js:38:13)
at exports.SitesGenerator._extractTranslations (/Users/agrow/repo/jamboree/src/commands/build/sitesgenerator.js:314:10)
at processTicksAndRejections …
```
=> Throw an error if the translationFile for a locale is invalid

.eslintrc.json, package-lock.json, package.json
This PR adds ESLint to Jambo, a linting framework for Javascript. This will
help make sure that any code added to Jambo adheres to our style guidelines
and best practices. For now, I've enabled only a couple of rules:
- All quotes must use be wrapped in single quotes.
- Named functions do not have a space between function name and the opening
'('.
As our style evolves, we will codify it by adding more rules to ESLint. In
my next PR, I will ensure that the Jambo codebase adheres to these rules and
that ESLint is run as part of 'npm run test'.
TEST=none
=> Add Javascript linting to Jambo.

.eslintrc.json, package.json, src/cli.js, src/commands/build/sitesgenerator.js, src/commands/card/cardcreator.js, src/commands/directanswercard/directanswercardcreator.js, src/commands/import/themeimporter.js, src/commands/init/repositoryscaffolder.js, src/commands/override/themeshadower.js, src/commands/page/add/pagescaffolder.js, src/commands/upgrade/themeupgrader.js, src/errors/systemerror.js, src/errors/usererror.js, src/utils/jamboconfigutils.js, tests/utils/envvarparser.js
This PR adds a couple of new rules to the ESLint config:
- 'max-len' enforces a line length of 90 characters (I've excluded 'require'
statements).
- 'quote-props' ensures we don't wrap object keys in quotes unless
absolutely necessary.
I have also included the changes needed to make the code compliant with all
of the ESLint rules. You can automatically fix some linting errors with
'eslint -fix'. Lastly, linting is now run as part of 'npm run test'.
TEST=auto
Made sure 'npm run test' did not report any issues.
=> Add additional linting rules and ensure codebase compliance.

src/commands/build/globalconfiglocalizer.js, src/models/localizationconfig.js, tests/commands/build/globalconfiglocalizer.js, tests/models/localizationconfig.js
Previously, we assumed that each locale in the 'locale_config' would need
the ability to specify a localized 'apiKey'. This assumption was not correct.
The 'apiKey' is the same for all experiences in a business. There will be
different experiences per locale, but the 'apiKey' is constant. Because it
is something that is business-specific, we will now only allow it in the
'global_config' file. Any 'apiKey' in 'locale_config' will be ignored.
J=SLAP-640
Fixed and ran unit tests. Created a site with English and French page sets.
Set the 'apiKey' only in the 'global_config' and saw it used for both locales.
=> Allow 'apiKey' only in the 'global_config' file.

src/commands/build/sitesgenerator.js
These are from the Answers SDK. In some cases, we need to compare two things and these helpers make doing that much more convenient. Example usages of these include:
```hbs 
{{#if (eq value 'expectedValue')}}...{{/if}}
{{#unless (gt value 'maxValue')}}...{{/if}}
```
There are several expressions in the theme that could use these; but the impetus for this change is adding the locale prefix to the SDK bundle for locales that are not English, ([PR here](https://github.com/yext/answers-hitchhiker-theme/pull/317)) e.g. 
```hbs
{{#unless (eq sdkBundleLocale 'en')}}{{sdkBundleLocale}}-{{/unless}}answerstemplates.compiled.min.js
```
TEST=manual
J=SLAP-633
Run `jambo build` using each of helpers in a test .hbs file. Inspect output .html files and verify that the logic is correct.
=> Add comparison and boolean Handlebars helpers

src/commands/build/sitesgenerator.js
TEST=manual
J=SLAP-626
Use helper in a jambo site, test adding param to the global_config: `"alexis-text-param": "static/assets/image.png"` then putting this snippet in the Handlebars.
```hbs
{{#if (matches global_config.alexis-text-param 'static\/assets\/[^"]*' )}}
works!
{{/if}}
```
Inspect output HTML and see "works!" in the file. Change "if" to "unless" and see that "works!" is no longer in the output file.
=> Add jambo matches Handlebars helper

src/handlebars/handlebarspreprocessor.js, tests/fixtures/handlebars/processedcomponent.js, tests/fixtures/handlebars/processedtemplate.hbs, tests/handlebars/handlebarspreprocessor.js
Rename the output of the transpilation calls to match the new names in the SDK
The translateJS helper now creates calls to ANSWERS.processTranslation() rather than ANSWERS.translateJS(). The translate HBS helper creates calls to a processTranslation helper rather than translate helper in the SDK.
J=SLAP-654
TEST=manual, auto
Update unit tests and confirm they pass. Build an internationalized ANSWERS site with the [corresponding SDK branch](https://github.com/yext/answers/pull/1077) and observe a properly translated site.
=> Rename output of transpilation calls

.github/workflows/run-tests.yml
This commit add a GH workflow called 'Run Tests'. This workflow is configured to run our suite of Jest tests against any PR targeting master.
=> Add a GH workflow for running our Jest tests

src/commands/build/sitesgenerator.js
Currently if we try to use the "matches" helper with a variable that does not exist, it fails. For example:
```hbs
{{#if (matches thisVariableDoesNotExist 'test')}}{{/if}}
```
throws an
```
TypeError: Cannot read property 'match' of undefined
at Object.<anonymous> 
...
```
Error. 
TEST=manual
J=SPR-667
Use handlebars helper with variable that does not exist. Confirm it returns false (rather than causing the jambo build to fail)
=> Add null check to matches handlebars helper

src/handlebars/handlebarspreprocessor.js, src/i18n/translator/translator.js, tests/fixtures/handlebars/processedcomponent.js, tests/fixtures/handlebars/processedtemplate.hbs, tests/fixtures/handlebars/rawcomponent.js, tests/fixtures/handlebars/rawtemplate.hbs, tests/handlebars/handlebarspreprocessor.js, tests/i18n/translator/translator.js
Update the transpilation of runtime calls calls to no longer create stringified json
For calls to ANSWERS.processTranslation(), pass an object as the first parameter rather than stringified JSON. For calls to the processTranslation HBS helper, instead of passing pluralizations through the phrase param, pass pluralForms as their own parameters. This simplifies our escaping logic to only require the escaping of single quotes. Also, no longer create a locale parameter when creating transpiled calls.
J=SLAP-638
Update unit tests and confirm they pass. Run an internationalized jambo build with the corresponding branch in the SDK and verify that the translations are correct. Also inspect the HTML generated through the jambo build to verify that the calls to the helpers are …
=> Update output of transpilation calls

src/i18n/translator/translator.js, tests/fixtures/translations/fr-FR.po, tests/i18n/translationfetchers/localfileparser.js, tests/i18n/translator/translator.js
Use escapeRegExp rather than escapeInterpolationBrackets for plural translation key.
There was a bug where the following translation was not being translated properly:
msgid "([[resultsCount]] result)" msgid_plural "([[resultsCount]] results)" msgstr[0] "[[resultsCount]] resultado" msgstr[1] "[[resultsCount]] resultados"
The translation was failing due to the open and closing parentheses being interpreted as a regex capture group during the key lookup. This was because we manually check translation keys inside i18next with a regex test for plural translations. Use lodash.escapeRegExp to solve this issue and escape all other possible RegExp characters.
J=none
TEST=auto
Add a test that confirms the parentheses are properly escaped. Confirm that all other translations still work properly.
=> Use lodash escapeRegExp on plural translation keys

src/cli.js, src/commands/commandimporter.js
This PR creates the CommandImporter class. The class imports all custom
Commands in a Jambo repo. A custom Command can be either repo or Theme
specific. Custom Commands from the repo itself are housed in a top-level
'commands' directory. The Theme's custom Commands live in the 'commands' folder
under the Theme. If the same Command is specified in both the repo and the
Theme, Jambo prefers the one from the repo. This way, Theme Commands can be
overriden.
Internally, the CommandImporter merges both 'commands' directories. It then
treats all top-level files in the merged directory as exporting a Command
for Jambo. This is a convention we will make clear in documentation. This
mechanism makes it possible for people to use 'override' to create shadows
of Theme Commands or their helpers. As …
=> Support for importing custom Commands and adding them to the Registry.

src/commands/build/sitesgenerator.js
These helpers are present in the Theme's cards, but since they aren't registered with Jambo's Handlebars renderer we are unable to use them outside of templates for Answers components. 
TEST=manual
=> Add 'any' and 'all' Handlebars helpers

src/commands/build/pagewriter.js
This commit updates relativePath to be "." instead of ""
when the page output path is the root output dir.
J=SLAP-773
TEST=manual
check that on a new hh-theme page with no locale_config,
bundle.js and a favicon can load correctly
=> Default relativePath to "." instead of ""

src/cli.js, src/commands/commandimporter.js
For cases when commands are run pre-theme import, the CommandImporter would fail (an example of this is the `jambo import --theme` command). This is because the second case in [this ternary](https://github.com/yext/jambo/blob/master/src/cli.js#L27) doesn't have a theme to pass into the constructor. The theme param should be last since it's optional.
TEST=manual
Run `jambo import --theme answers-hitchhiker-theme` before this, see error. Run again after, see theme import successfully.
=> Swap order of params in CommandImporter constructor

src/models/localizationconfig.js, src/models/pagetemplate.js, src/utils/configutils.js, src/utils/i18nutils.js, tests/models/localizationconfig.js, tests/models/pagetemplate.js, tests/utils/i18nutils.js
Adds canonicalization logic to normalize casing and locale code separators. This logic converts the language in the locale to lowercase and the region (if provided) to uppercase. Replaces dashes with underscores.
TEST=manual
J=SLAP-705
Test with varied casing in config names and page names.
=> Canonicalize locales

src/commands/build/sitesgenerator.js, src/i18n/translationfetchers/localfileparser.js, tests/i18n/translationfetchers/localfileparser.js, tests/i18n/translator/translator.js
Modify translation file loading so that all custom translation files are not strictly necessary
Modify localFileParser so that it no longer tries to default the file name if just a locale is provided. Modify the site generator to always load theme translations, and to only load custom translations if the "translations" dir is configured. A custom translation file for each configured locale is no longer required.
J=SLAP-706
TEST=manual
Test a jambo build with and without custom translation dirs and custom translations file paths. Confirm translations are correct. Test that only some of the translation files for the configured locales can be present when building a site.
=> Translation loading improvements

src/models/localizationconfig.js
Was running into this issue on SGS, using a the locale_config
from the diageo repo, which had a non canonical default locale.
J=SLAP-776
TEST=manual
see that builds run again
=> Canonicalize the default locale

src/commands/commandimporter.js
Updates the command importer to use ensureDirSync
from fs-extra instead of regular mkdirSync. The
live preview containers don't have a output
directory, since it's not tracked.
J=SLAP-776
TEST=manual
tested that SGS live preview works again
=> Use ensureDirSync for merging jambo custom commands

src/commands/commandregistry.js, src/commands/extract-translations/jambotranslationextractor.js, src/models/commands/argumentmetadata.js, tests/commands/describe/describecommand.js
Convert existing extract-translations command into a class that implements Jambo's new 'Command' interface.
TEST=manual
Run `jambo --help`, see `jambo extract-translations  extract translated strings from .hbs and .js files` in the list of commands.
Run `jambo extract-translations --help` and see the following printed:
```
jambo extract-translations
extract translated strings from .hbs and .js files
Options:
--help     Show help                                                 [boolean]
--version  Show version number                                       [boolean]
--output   the output path to extract the .pot file to
[string] [default: "messages.pot"]
```
Run `jambo describe` and see the following in the list of commands described:
```
'extract-translations': {
displayName: 'Extract …
```
=> Add extract-translations command

package-lock.json, package.json, src/commands/upgrade/themeupgrader.js
The Jambo 'init' command was not working properly after cutting over all
built-in commands to the CommandRegistry. When 'init' (or any other command)
is run, Jambo first attempts to instantiate all the built-in commands. This
is done in the CommandRegistry. Unfortunately, the ThemeUpgrader command could
not be created without a 'jambo.json', leading to a Catch 22. This then led
to the registry erroring out and the 'init' command failing to proceed. To fix
this, we make it so that the ThemeUpgrader can be safely created before 'init'
is run.
The current pattern in CommandRegistry._initialize is okay for now. When run,
the commands already graceully handle failures like a missing 'jambo.json'.
Long term, I think the real fix here is to change our pattern. In the Command
interface, we can …
=> Fix bug preventing 'init' from working properly.

src/commands/describe/describecommand.js, src/commands/upgrade/themeupgrader.js, tests/commands/describe/describecommand.js
Makes changes to provide the `jambo upgrade` command an optional
`branch` argument. This argument will specify a branch to upgrade
the theme to, instead of always upgrading to the HEAD of master.
J=SLAP-789
TEST=manual
Performed a `jambo upgrade --branch [branch_name]` using several
different branches to verify that the theme was upgraded to have
changes from the specified branch.
=> commands: give upgrade command optional branch arg

src/commands/commandregistry.js, src/commands/page/add/pagecommand.js, src/commands/page/add/pageconfiguration.js, src/commands/page/add/pagescaffolder.js
Adds a locales argument that can be passed into the page command.
The locales argument takes an array of locales, e.g. es, fr, it.
The page command's describe method returns an array of locales
found in config/locale_config.json.
J=SLAP-793
TEST=manual
When I run `jambo page` with the locales arg, such as
`jambo page --name test-locales --template vertical-standard --locales es fr`,
I see that es and fr configs are created for the test-locales in page in
addition to test-locales.json.
When I run `jambo describe` in a repo that has a locale_config.json
file with es and fr locales, I see that the page command returns
es and fr as options for the locales arg.
=> page cmd: add locales argument

src/commands/upgrade/themeupgrader.js
When there is no jambo config present and we are attempting to get
a theme's branches, the method should return an empty array.
This prevents an issue of running `jambo describe` and getting an
error before `jambo init` is run in a directory.
TEST=manual
Ran a `jambo describe` in an empty directory and see that results
are returned instead of an error.
=> upgrade command: return empty array for branches if no jambo config

src/commands/page/add/pagecommand.js
Makes a change to use the comment-json package's parse function
when parsing locales from locale_config.json.
We need to use the comment-json package because the default
imported locale_config.json contains comments, which the
built-in JSON.parse thinks is invalid.
TEST=manual
Ran `jambo describe` in a repo that has a locale_config.json with
comments and saw that no errors occurred and that the locales
were returned correctly.
=> page command: use comment-json to parse locale_config.json

src/commands/import/themeimporter.js
We add formatters-custom.js so HHs can update the file without having to
override the theme.
In the future, hopefully changes like this will only have to be in the
theme with the power of our new custom commands
J=SLAP-810
TEST=manual
On a new site that's been `jambo init`ed, import the HH theme. Make sure
that the js folder exists in the top-level static folder and that it has
the formatter-custom.js file. (In my case, formatters-custom didn't
already exist yet so I tested with formatters.js).
=> themeimporter: Add formatters-custom.js as static file

src/cli.js, src/commands/build/buildcommand.js, src/commands/commandimporter.js, src/commands/commandregistry.js, src/commands/describe/describecommand.js, src/commands/extract-translations/jambotranslationextractor.js, src/commands/import/themeimporter.js, src/commands/init/initcommand.js, src/commands/override/overridecommand.js, src/commands/page/add/pagecommand.js, src/commands/upgrade/themeupgrader.js, src/models/commands/command.js, src/yargsfactory.js, tests/commands/describe/describecommand.js
Changes all Jambo commands so that every method except `execute`
is static.
This change is so that the cli will not need to instantiate a
command unless it actually needs to execute it.
Also updates the command interface so that all methods except
execute are static.
J=SLAP-817
TEST=manual
Ran all jambo commands and saw that there were no changes in behavior.
=> commands: all methods except execute are static

src/commands/describe/describecommand.js, tests/commands/describe/describecommand.js
The `describe` command was logging a JS object to the console. This format was not parsable by SGS. This PR updates `describe` so that JSON is logged instead. 
J=SLAP-854
Updated the `describe` unit tests. Also ran the command on a test repo and saw the expected output.
=> Ensure that the 'describe' command outputs JSON

package-lock.json, package.json, src/commands/build/sitesgenerator.js
This is needed in the theme. When custom hbs helpers are implemented,
this can be cut over.
J=SLAP-861
TEST=manual
test that urls like //yext.com will still be recognized as absolute
test using a data:image/gif;base64, url for favicon
=> add isAbsoluteUrl helper

package-lock.json, package.json, src/commands/build/sitesgenerator.js
This commit updates the isAbsoluteUrl helper to recognize
urls like "/my-img.svg" as absolute urls. On a random website,
say yext.com, that url will point to yext.com/my-img.svg no matter
what page it is on.
Theme PR this is needed here
https://github.com/yext/answers-hitchhiker-theme/pull/482
will upgrade jambo ver once this is merged in
T=https://yextops.zendesk.com/agent/tickets/366842
J=SLAP-881
TEST=manual
test that the WHO site can specify an iconUrl that points to a static
asset
tested that a fresh site can also specify an iconUrl in a CTA
that points to a static asset, and also can directly put in
img tags with a static asset src
=> Recognize urls that start with only 1 slash as absolute

src/cli.js, src/commands/commandimporter.js
This PR adds a validation step to the `CommandImporter` class. This step
ensures that what is `require`'d adheres to the `Command` interface. If the
imported object is invalid, a warning is printed to the console. The invalid
command is not added to the `CommandRegistry`.
J=SLAP-888
TEST=manual
Tested the following scenarios:
- Created a test repo with Theme 1.16 and the latest Jambo. Ran various
Jambo commands in the repo and they worked as expected. Each time a command
(or `--help` or `version`) was run warnings were printed to the console. These
indicated the Theme's custom commands could not be parsed by Jambo.
- Created a test repo with Theme 1.17 (beta) and the latest Jambo. Ran various
commands and all passed. No warnings about invalid custom commands were
in the console. The …
=> Add validation when importing custom commands.

src/cli.js, src/commands/commandregistry.js
Previously, Jambo would always import custom commands, even if they weren't
necessary. Importing these commands and adding them to the CLI is only required
if `--help`, `describe`, or a command not part of the built-in set, is run.
This PR updates the `cli.js` file to only import and add custom commands to the
registry under these three circumstances.
I also took this oppurtunity to refactor the `cli.js` file. There are now
methods for each step of the CLI initialization process.
J=SLAP-888
TEST=manual
Tested these scenarios:
- Invoked Jambo without adding an actual command.
- Invoked `--help` and saw the expected output. This was done in an initialized
and uninitialized repo.
- Invoked `describe` and saw the expected output. This was done in an
initialized and uninitialized repo.
- …
=> Only add custom commands to the CLI instance when necessary.

src/yargsfactory.js
Previously, every type of option was added to Yargs using `yargs.option`. But,
Yargs has special, different syntax for registering Array-type options. This
PR ensures we uses that syntax whenever `ArgumentMetadata.getType` is `ARRAY`.
TEST=manual
Tested the following scenarios:
- An array-type option is added to Yargs correctly.
- A string-type option is still added to Yargs correctly.
- When no explicit default is specified, an Array-type option defaults to `[]`.
=> Add specific logic to construct Array-type options in the CLI.

package-lock.json, package.json, src/cli.js
The logic for determining if custom commands should be imported had a small
bug. When `jambo --version` was invoked, Jambo attempted to import custom
commands and register them with the CLI. This behavior was incorrect.
TEST=manual
Made sure that `--version` did not cause custom commands to be imported and
added to the registry.
=> Correct logic for determining if custom commands should be imported.

package-lock.json, package.json, src/commands/build/sitesgenerator.js
The helper also matches on root relative links,
which are technically not "absolute"
=> rename hbs helper isAbsoluteUrl to isNonRelativeUrl

src/commands/import/themeimporter.js
It looks like this param was accidentally changed to
--addThemeAsSubmodule some time ago, this commit
reverts this change so that theme importer is consistent
with its describe output (and also the theme sync script).
TEST=manual
try importing a theme with --addAsSubmodule false, no error
try importing a theme with --addThemeAsSubmodule false, jambo
complains about unknown argument
=> Revert import --addAsSubmodule param name change

src/handlebars/registerhbshelpers.js, tests/handlebars/registerhbshelpers.js
This commit adds back the isAbsoluteUrl helper, which was
renamed to isNonRelativeUrl. This is needed to support
theme 1.16 doing an npm upgrade jambo.
Will cherry pick to support/v1.9
TEST=manual, auto
test that I can build a site using both helpers
=> add back isAbsoluteUrl helper (alias of isNonRelativeUrl)

src/commands/upgrade/themeupgrader.js
Small fix for upgrading a theme that was imported
as a submodule. Will cherry-pick to support/v1.9
TEST=manual
test that I can upgrade submodule themes again
=> upgrade: specify submodulePath in git submodule set-branch

src/validation/pageconfigsvalidator.js
Noticed in a slack post it was missing spaces.
TEST=none
=> Add missing spaces to page config validator error msg

src/commands/import/themeimporter.js, src/commands/override/themeshadower.js, src/commands/upgrade/themeupgrader.js, src/utils/customcommands/commandexecuter.js, src/utils/fileutils.js, tests/utils/fileutils.js
This commit adds the postimport hook to jambo
import, and removes the default postimport
logic (which has been moved to the theme).
We can remove the logic in this specific case,
because anybody who calls jambo import will
be importing the newest version of the theme,
which will already have the postimport logic
moved into it.
This commit allows users to specify a postimport.js
(or any file extension, e.g. postimport.sh) script
to be run after an import.
This PR also updates the postupgrade script to have
the same capability (i.e. you can now specify an
upgrade.sh, instead of upgrade.js)
Finally it adds stdout, stderr, and error handling
to the commandexecutor, which might be renamed to
something like scriptexecutor in a separate PR,
now that we have custom jambo commands.
J=SLAP-833 …
=> Add postimport hook, remove default postimport

src/validation/rawconfigvalidator.js
PageConfigsValidator checks that all page configs have
a corresponding locale in the locale_config.
When parsing locales from page config file names, it was
calling parseLocales in i18nutils, which will canonicalize
the locale. However it was no canonicalizing the locale
when pulling them down from the locale_config.json
will cherry-pick to support/v1.9
J=SLAP-936
TEST=manual
test that I can specify a locale like en_gb or en_Gb
on the weight watchers repo and jambo will build the en_GB
page correctly
=> rawconfigvalidator: canonicalize locales when pre-validating

src/commands/upgrade/themeupgrader.js
The `upgrade` command implicitly assumes a default of `master` for the
`branch` parameter. That was not getting communicated to SGS because we left it
out of the command's `describe`. I added some additional logic so that we don't
list any default for `branch` when the repo has no Theme yet. It looked a bit
weird to have no options listed for `branch`, but a default of `master`.
J=SLAP-978
TEST=manual
Ran `describe` on an empty repo and saw no default listed for `branch`. Ran
`describe` on a repo with a Theme and saw a default of `master` reported. Also
ensured that running `upgrade` with no `branch` resulted in `master` being
used.
=> Upgrade command's `describe` should list a default for `branch`.

src/commands/import/themeimporter.js, src/commands/init/repositoryscaffolder.js
Fixes the issue where a user cannot run a `jambo init` with the
theme specified.
The usage of the theme importer as a constructor was originally
incorrect in the repository scaffolder; the change is made here
to use it correctly.
TEST=manual
Created a new directory locally, `cd`-ed into it, and ran
`jambo init --theme answers-hitchhiker-theme`. Saw that the
jambo repo was initialized correctly and that the theme was
also imported into the repo.
=> themeimporter: fix not being able to init with theme

package-lock.json, package.json
- Fixed a bug that caused `init` to fail when the `--theme` flag was used.
(#182)
- Update the `describe` command so that it correctly lists `master` as the
default of `upgrade.params.branch`. (#183)
=> Version 1.9.8.

src/commands/commandimporter.js
Jambo should support both the current and old style of importing a custom
command. The legacy style, which can be seen in Theme v1.16, didn't export a
class, but a function. The function took in a jambo config and provided an
instance of the custom command's class. Further, back then, the command class
did not have any static members.
The `CommandImporter` is now able to detect legacy command imports. It wraps
them in an implementation of the latest `Command` interface. Note that all
legacy imports were characterized by a function starting with 'jamboConfig =>'.
J=SLAP-942
TEST=manual
Tested the following for sites on Theme v1.16 and Theme v1.18:
- `jambo --help` produced the expected output.
- The `--help` flag on the `card` and `directanswercard` commands worked as
expected.
- The …
=> Add legacy support for the older style of custom command importing.

src/models/partialsregistry.js, src/utils/fileutils.js, tests/utils/fileutils.js
Ignore node_modules when registering partials
When adding the [theme testing site](https://github.com/yext/answers-hitchhiker-theme/pull/555), I ran into a problem as jambo would try to register the files inside node modules. Ignoring paths that contain node modules when registering partials fixes this issue.
J=none
TEST=manual
Build the testing repo and observe a successful build
=> Ignore node modules partials

package-lock.json, package.json, src/commands/upgrade/themeupgrader.js
The `ThemeUpgrader.describe` method would attempt to fetch the branches for the
default Theme. The branches would be listed as the various options for the
`--branch` flag. The problem was that the method for fetching the branches
did not work unless the Theme was imported as a sub-module. Rather than fix
the logic to work for all cases, we decided this was outside Jambo's realm of
responsibility. If someone is using a Theme, they should be able to tell Jambo
which branch to use. Jambo does not need to supply them with a list of the
valid options. As such, `describe` now lists the `branch` param as a normal
string, not asingleoption.
This is considered a bug fix, so the Jambo version was incremented by x.x.1.
J=SLAP-1047
TEST=auto,manual
Reran all Jambo unit tests. Verified the following …
=> Remove ability of `upgrade` command to fetch Theme branches.

src/utils/gitutils.js
This PR updates the getRepoForTheme method to use the HTTPS protocol instead
of SSH. Recently, the Theme was made public. The hope was that this meant
the Preview containers in CBD would not need an SSH key anymore. But, if the
SSH protocol is used, an SSH key is still required, even though the Theme
repo is now public.
TEST=manual
Removed my local machine's SSH key from Github and verified that I could still
import and upgrade the Theme in a Jambo site.
=> Update getRepoForTheme to use HTTPS instead of SSH.

src/commands/commandimporter.js
Ensure that files end with '.js' before trying to load the module
This fixes a bug where jambo would crash if a .DS_Store file was present in the commands folder.
J=none
TEST=manual
Test that jambo no longer crashes if a .DS_Store file is present in the command folder. Test the `jambo --help` command, the `jambo describe` command, and the custom vertical command from the theme.
=> Only load javascript files for custom commands

src/handlebars/handlebarspreprocessor.js, src/handlebars/invocationtranspiler.js
This commit refactors the new InvocationTranspiler class out of
the HandlebarsPreprocessor. This work ended up not being strictly
needed for using the Handlebars parser to parse out translate helper
usages, but I still thought it was a nice tech debt change.
No new functionality was added, just a number of methods were split
off into InvocationTranspiler.
J=SLAP-1178
TEST=manual
test building a site with translation helpers
also see that multiline translation helpers still fail to build
=> Refactor InvocationTranspiler out of HandlebarsPreprocessor

.github/workflows/run-tests.yml
Previously, this was set to only run on pull request into master.
Instead, it should run on pull requests into any branch, and also on any subsequent pushes
to a pull request (this is the same as we have it on other repos).
This way we run tests both on what the repo would look like after the branch is merged,
and also on the branch itself.
TEST=auto
test that PRs and additional pushes to PR won't run tests without this change
=> fix run-tests workflow not running

README.md, src/commands/import/themeimporter.js, src/commands/init/repositoryscaffolder.js, src/commands/upgrade/themeupgrader.js, src/utils/gitutils.js, src/utils/thememanager.js
Add a --themUrl option to the import command
The theme URL is now the preferred way to import a theme. This PR deprecates specifying a theme name directly.
J=SLAP-1136
TEST=manual
Test importing by HTTPS URL, SSH URL, and by theme name. Confirm that an error is thrown if neither a URL or a theme name are supplied. Confirm that an error is thrown if a URL is not supplied and the theme isn't known by jambo. Test that if both URL and theme are supplied, the URL is used. Test an upgrade. Observe the output of `jambo import --help` and `jambo describe`
=> Support importing by specifying a URL

src/commands/init/initcommand.js, src/commands/init/repositoryscaffolder.js
Allow a themeUrl to be passed to the init command
This is adds the same functionality that #205 does for the import command, except this is for the init command
J=SLAP-1136
TEST=manual
Test importing by theme URL, and by theme name. Confirm that init works if neither a URL or a theme name is supplied. Confirm that an error is thrown if a URL is not supplied and the theme isn't known by jambo. Test that if both URL and theme are supplied, the URL is used. Observe the output of jambo init --help and jambo describe
=> Add themeUrl param to the init command

README.md, src/commands/import/themeimporter.js, src/commands/init/initcommand.js, src/commands/init/repositoryscaffolder.js, tests/commands/describe/describecommand.js
This commit renames the --addAsSubmodules param of jambo import and init to
--useSubmodules, and changse the default to false.
J=SLAP-1135
TEST=manual
test that I can import a theme with useSubmodules, and it will be a submodule
test jambo import --theme answers-hitchihker-theme and see it will be imported
as regular checked in files, with the a .git folder removed. check that I can commit
the theme changes without any errors/warning messages, which you would see if
you tried the .git folder wasn't removed
test importing a theme on init, but as submodule and as regular files
=> rename addAsSubmodules to useSubmodules, false by default

package.json
This PR adds `engines.node` to the `package.json`. This property
allows us to specify the Node version(s) that work with a given
Jambo version. If a user tries to npm install Jambo with an
incompatible Node version, they will receive an error and the
install will fail (assuming they have `engine-strict` enabled).
A change will be made to the Template repos to ensure that it
includes a .npmrc file with `engine-strict`.
TEST=manual
Tried installing Jambo in a local repo with Node 10. I saw an error
indicating my Node version did not meet Jambo's requirements. When
I switched to Node 12, I was able to install it without issue.
=> Codify the minimum required Node version for Jambo.

src/buildJamboCLI.js, src/cli.js
This commit factors out the buildJamboCLI() method
from cli.js. No functional changes have been made.
This method will be used by the upcoming acceptance test
infrastructure, to create test jambo instances.
J=SLAP-992
TEST=manual
test that I can still build pages with jambo
test that jambo still logs 'You must provide Jambo with a command.'
if you don't enter a command
test that custom commands still work
=> factor out buildJamboCLI() from cli.js

src/commands/build/buildcommand.js, src/commands/import/themeimporter.js, src/commands/init/initcommand.js, src/commands/init/repositoryscaffolder.js, src/yargsfactory.js
This commit allows command handlers to be async, so that
upcoming acceptance test infrastructure can run multiple
commands one after another in the same process.
It also updates the init and import commands to perform
git operations within the current working directory, instead
of the initial directory jambo was called in. This is needed so that
acceptance tests can use jambo in a directory different than 
the one the acceptance tests live in. It also will be useful if we
ever release a Jambo API, so that Jambo can be called programmatically
in JS.
This does not change Jambo's behavior when only one
command is run per process, which is what normally happens.
J=SLAP-992
TEST=manual
test that custom commands work, init works, import works, and build works
=> allow async command handlers, use cwd for git ops

.github/workflows/coverage.yml, README.md, jest-coverage.json, package.json
Adds a code coverage workflow using Coveralls.
Because the acceptance tests are ran using jest, and are run
in the main thread (i.e. no spawnSyncs), the acceptance tests
count towards our coverage. Acceptance test coverage is probably
of a lower overall "quality" than our unit test coverage, since it's
not as rigid about checking output values.
Also adds a code coverage badge to the readme.
J=SLAP-873
TEST=auto
=> add Coveralls github workflow

src/handlebars/registerhbshelpers.js
This PR adds a check to the `babel` helper to see if we are currently in the Development Mode. If
so, the enclosed source code is not run through Babel, it is returned verbatim. This is a preview
optimization, since the Babel-ification is a relatively slow operation. It's not necessary for
preview either, assuming devs are not previewing their changes in IE11.
J=SLAP-1312
TEST=manual
Ensured that when in Development mode, the helper was a simple pass-through. In Production mode,
the enclosed code was Babel-ified.
=> Do not run the `babel` helper in Development Mode.

src/handlebars/registerhbshelpers.js
This PR adds a check to the `babel` helper to see if we are currently in the Development Mode. If
so, the enclosed source code is not run through Babel, it is returned verbatim. This is a preview
optimization, since the Babel-ification is a relatively slow operation. It's not necessary for
preview either, assuming devs are not previewing their changes in IE11.
J=SLAP-1312
TEST=manual
Ensured that when in Development mode, the helper was a simple pass-through. In Production mode,
the enclosed code was Babel-ified.
=> Do not run the `babel` helper in Development Mode. (#224)

package-lock.json, package.json, src/buildJamboCLI.js, src/cli.js, src/commands/build/pagesetsbuilder.js, src/commands/build/pagewriter.js, src/commands/build/sitesgenerator.js, src/commands/commandimporter.js, src/commands/extract-translations/jambotranslationextractor.js, src/commands/import/themeimporter.js, src/commands/upgrade/themeupgrader.js, src/errors/systemerror.js, src/errors/usererror.js, src/models/configurationregistry.js, src/utils/errorutils.js, src/utils/logger.js, src/yargsfactory.js, tests/acceptance/setup/TestInstance.js, tests/acceptance/suites/basic-flow.js
This commit refactors jambo's logging to use npmlog,
which is the logger used by npm (surprise!).
It adds a magenta 'jambo' log heading to differentiate it from
npm, which uses a white on black 'npm' heading.
J=SLAP-226
TEST=manual
test a regular jambo build
test jambo build when it throws an error because there's no jambo.json
test jambo page that is missing required arguments
test the custom card command in the theme
see that the tested logs look as expected, and contain the same information as before
jambo help prints normally
jambo version prints normally
warning is given if custom command is malformatted
test that you can set the npmlog log level anywhere, and that log level will be reflected globally
in the future we can let jambo set different log levels or even silence logging
=> use npmlog for logging with colors

src/commands/build/pagewriter.js, src/commands/build/sitesgenerator.js, src/commands/build/templatedatavalidator.js, tests/commands/build/templatedatavalidator.js, tests/fixtures/hooks/templatedatavalidator.js
- Added another operation inside PageWriter to ensure template data is correct
using TemplateDataValidator, which pass in the formatted config data to the theme's validation
hook function
J=SLAP-1369
TEST=auto
Created Jest tests using default config format with/without missing field when
pass to validation hook and check if errors are handle properly
=> Add Jambo build validation hook

package-lock.json, package.json, src/commands/extract-translations/defaulttranslationglobber.js, src/commands/extract-translations/jambotranslationextractor.js, src/i18n/extractor/translationextractor.js, src/utils/gitutils.js, tests/acceptance/fixtures/describe/describe-test.json, tests/acceptance/fixtures/extract-translations/custom-globs.pot, tests/acceptance/fixtures/extract-translations/default.pot, tests/acceptance/suites/extract-translations.js, tests/acceptance/test-themes/basic-flow/translations/lonewolf.hbs, tests/acceptance/test-themes/basic-flow/translations/translation-folder/ignored.hbs, tests/acceptance/test-themes/basic-flow/translations/translation-folder/template.hbs, tests/i18n/extract/defaulttranslationglobber.js, tests/i18n/extract/translationextractor.js
This commit updates the extract-translations command
to take in a --globs argument.
The TranslationExtractor was refactored to only take in
a glob, instead of taking in arrays of files, directories,
and ignored files. The logic of creating an array of globs
by reading from the jambo.json and gitignore files has
been moved into the DefaultTranslationGlobber.
simple-git was updated from 1.131 to 2.40 to remove git
ENOENT errors during acceptance tests. There were improvements
to how simple-git performs git operations in parallel after v2.
We only use simple-git for very basic operations like cloning,
init-ing, and checking out submodules, staging files, and committing,
so there shouldn't be any issues with upgrading. The only breaking
changes in v2.0.0 are git.log using strict ISO by …
=> add --globs param to extract-translations cmd

tests/acceptance/suites/locale-fallback.js, tests/acceptance/test-themes/basic-flow/postimport.js, tests/acceptance/test-themes/customcommand/postimport.js, tests/acceptance/test-themes/locale-fallback/config/locale_config.json, tests/acceptance/test-themes/locale-fallback/postimport.js, tests/acceptance/test-themes/locale-fallback/script/core.hbs, tests/acceptance/test-themes/locale-fallback/templates/universal-fallback/markup/directanswer.hbs, tests/acceptance/test-themes/locale-fallback/templates/universal-fallback/page-config.json, tests/acceptance/test-themes/locale-fallback/templates/universal-fallback/page.html.hbs, tests/acceptance/test-themes/locale-fallback/templates/universal-fallback/script/directanswer.hbs, tests/acceptance/test-themes/locale-fallback/templates/universal-standard/markup/directanswer.hbs, tests/acceptance/test-themes/locale-fallback/templates/universal-standard/page-config.json, tests/acceptance/test-themes/locale-fallback/templates/universal-standard/page.html.hbs, tests/acceptance/test-themes/locale-fallback/templates/universal-standard/script/directanswer.hbs
Created locale fallback acceptance test
- created a new test-theme folder `locale-fallback` with locale_config.json that contains 3 locales: en (default locale), fr (locale fallback for es), and es.
- 'locale-fallback' acceptance test: use `locale-fallback` theme and create an index page for en and es, `index.html.hbs` and `index.fr.html.hbs,` using two different templates. When executing jambo page command for en index page, also create a pageConfig for es with the flag `--locales es`. See that es index page fall back on the pageTemplate and config file for fr.
J=SLAP-1303
TEST=auto
Set `procrastinateCleanup` to true when running the test. See that in the playground folder, the expected config files, pageTemplates, and public html files are build as expected for en, es, and fr. See that …
=> locale fallback acceptance test

src/utils/i18nutils.js, tests/acceptance/suites/themeupgrader.js, tests/utils/i18nutils.js
J=SLAP-1526
TEST=auto,manual
unit tests
ran build with zh-hans-ch in locale config, saw that the generated source code used the correct locale in the page
tried building a page with a locale with >3 sections, got a jambo warning but build continued without changing the locale
=> update canonicalizeLocale to handle 中文(chinese)

src/commands/build/templateargsbuilder.ts
Fixes a typo found by typescript
I was using sublime merge's "stage hunk" feature and the parameter types
were registered in the same hunk as the typo fix, and it didn't seem worth it to manually separate out
the commits.
=> fix typo templateDataFormattter -> templateDataFormatterHook

src/utils/errorutils.ts
The issue was that err.exitCode does not exist on the vanilla
Error class, only our augmented UserError and SystemError classes
=> update isCustomError to be a type guard

src/models/commands/command.ts, src/yargsfactory.ts
Adds return types to the base command class so typescript is happy.
The types could have been any, but it felt a little more correct to just
use the correct types.
Also update _createCommandModule desc -> describe, because desc doesn't
exist on the exported yargs types (though it appears to work so probably
just deprecated).
=> add return value types to base command class

src/handlebars/registerhbshelpers.ts
This prevents babel from automatically trying to use the babel.config.js
we added to jambo as part of the TS migration.
Our babel.config.js is only intended to be used by jest, not our built in
babel helper.
The import was already changed from `babel` to `{ transformSync }`.
We could keep the original babel import by turning on `allowSyntheticDefaultImports` in 
our tsconfig, but there doesn't seem to be too much point for that.
=> add configFile: false for babel helper

src/commands/build/sitesgenerator.ts, src/handlebars/registercustomhbshelpers.ts, tests/acceptance/test-themes/customcommand/commands/addVertical.js, tests/fixtures/hooks/templatedataformatter.js, tests/fixtures/hooks/templatedatavalidator.js, tests/handlebars/registercustomhbshelpers.js, tests/utils/i18nutils.js
jambo build is already an async command, so its easy to refactor
this dynamic require into a dynamic import statement.
The other dynamic requires in jambo are harder to refactor because
they live inside fully synchronous commands/methods, like our custom
commands importer.
TEST=manual
smoke test jambo (on a different branch that has all TS changes)
=> use es6 dynamic import for hbs helpers

src/utils/errorutils.ts
Previously, we defaulted err to the empty object, which would nicely
handle err being undefined. Typescript is happy with us defaulting it
to empty object, though, since it's not of type Error | SystemError | UserError.
TEST=manual
test that I can run jambo card, without all of the required params, and the
error will still printed nicely
=> handle undefined err in exitWithError

package-lock.json, package.json, src/utils/jamboconfigutils.ts
Unfortunately, we need this for backwards compatibility purposes. We used to
declare many of our helpers on the global namespace, and the global parseJamboConfig
was actually being referenced in answers-hitchhiker-theme
see https://github.com/yext/jambo/pull/19 and
https://github.com/yext/answers-hitchhiker-theme/pull/364
Also update some typescript and testing related deps
J=SLAP-1493
TEST=manual
tested the custom card command in the theme
see addToPartials work properly
=> define parseJamboConfig on the global namespace

package-lock.json, package.json, src/buildJamboCLI.ts, src/commands/LegacyAdapter.ts, src/commands/adaptCommandWithLegacyArgs.ts, src/commands/adaptLegacyCommand.ts, src/commands/build/buildcommand.ts, src/commands/commandregistry.ts, src/commands/describe/DescribeOutput.ts, src/commands/describe/describecommand.ts, src/commands/extract-translations/jambotranslationextractor.ts, src/commands/import/themeimporter.ts, src/commands/init/initcommand.ts, src/commands/override/overridecommand.ts, src/commands/page/add/pagecommand.ts, src/commands/upgrade/themeupgrader.ts, src/models/commands/ArgumentMetadata.ts, src/models/commands/Command.ts, src/models/commands/DescribeDefinition.ts, src/models/commands/commandexecutable.ts, src/yargsfactory.ts, tests/acceptance/fixtures/describe/describe-test.json, tests/acceptance/test-themes/customcommand/commands/addVertical.js, tests/commands/describe/describecommand.js, tsconfig.json
This commit updates describecommand to combine information from args
with the return value of describe (a DescribeDefinition) to produce
an instance of DescribeOutput, which is the full output to be used
by UI like sitesgitstorm.
J=SLAP-1493
TEST=manual,auto
test that all jambo card, page, vertical, and build commands work in SGS
test that I can run custom commands locally
=> unify describe with args

src/commands/build/sitesgenerator.ts, tests/commands/build/sitesgenerator.js
Log a warning during build when a custom or theme translation file is not found.
J=SLAP-1453
TEST=auto
Add jest tests and see that they pass successfully. Also build test-site with a non-existent translation file specified and see warning logged.
=> Warn when translation file is not found

src/commands/build/sitesgenerator.js
- fix bug for use case where a default locale specify custom translation file (e.g. 'ja_JP' use 'ja.po' file)
J=TECHOPS-2099
=> Allow custom translation for default locale

docs/jambo.command.describe.md, docs/jambo.command.md, etc/jambo.api.md, package-lock.json, package.json, src/commands/LegacyAdapter.ts, src/commands/adaptCommandWithLegacyArgs.ts, src/commands/adaptLegacyCommand.ts, src/commands/describe/describecommand.ts, src/models/commands/Command.ts, tests/commands/adaptCommandWithLegacyArgs.ts, tests/commands/adaptLegacyCommand.ts, tests/commands/describe/describecommand.js, tests/fixtures/customcommands/TestLegacyCommandNoDescribe.js, tests/fixtures/customcommands/TestLegacyCommandWithLegacyArgsNoDescribe.js
Make describe optional including for the legacy command interfaces
J=SLAP-1598
TEST=manual, auto
Use the theme test site and comment out the describe method. See that the command no longer shows up in the describe output. Test that when describe is not included, the command still works. 
Add unit test coverage
=> Make describe optional

src/i18n/translator/translator.ts, src/utils/i18nutils.ts, tests/i18n/translator/translator.js
Prior to this, certain kinds of chinese locales would not be translated properly.
i18next will silently refuse to translate for you if your locale has any underscores in it.
J=TECHOPS-2885
TEST=manual,auto
tested I can do zh-Hant_TW translations in the theme
=> add i18next specific locale formatting to support chinese

package-lock.json, package.json, src/utils/customcommands/commandexecuter.js
This PR resolves the following vulnerabilities
Bump `tmpl`'s version to 1.0.5 to avoid uncontrolled resource consumption when formatting a string
J=VULN-38389
TEST=auto
Ran npm run test. Also made sure running jambo commands locally works.
=> Resolve Vulnerabilities

package-lock.json, package.json, src/utils/customcommands/commandexecuter.js
- Addressed various vulnerabilities from our dependencies (#330, #332)
=> Version 1.12.5

.github/workflows/main.yml
Ubuntu 20.04 for Github Actions is being deprecated and will be fully unsupported on 2025-04-01. Update our semgrep action to the latest version.
=> Update semgrep main.yml to use ubuntu-latest
